version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries:
  - en
  - technical
  - python
words:
  - covdefaults
  - Craciun
  - fdel
  - FILECOVERAGE
  - Fira
  - fontawesome
  - FURB
  - inlinehilite
  - junitxml
  - kroki
  - linenums
  - magiclink
  - mkdocstrings
  - osxbit
  - Panaintescu
  - posargs
  - pymdownx
  - pypa
  - striphtml
  - stripnl
  - superfences
  - tasklist
  - techdocs
  - toxworkdir
  - twemoji
  - XDIST
ignoreWords: []
import: []
